config/routes.rb
Rails.application.routes.draw do
  get 'javascripts/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  namespace :openai do
    get 'tests/', to: 'tests#generate_text'
    get 'tests/show', to: 'tests#show'
  end

  namespace :fhir do
    resources :patients, only: [:index, :new, :create]
    resources :organizations, only: [:index]
    resources :encounters, only: [:index]
  end

  # Google_Healthcare_API
  get 'healthcare/index', to: 'healthcare#index'
  post 'healthcare/create_patient', to: 'healthcare#create_patient'


  get 'postcode/', to: 'post_codes#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many   :comments, dependent: :destroy
  # belongs_to :user, dependent: :destroy
  has_one_attached :image
  # validates  :title, presence: true, length: { maximum: 20  }
  # validates  :body,  presence: true, length: { maximum: 400 }

  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = @post.id
    comment.save
    redirect_to post_path(@post)
  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/fhir/patients_controller.rb
class Fhir::PatientsController < ApplicationController
  def index
    response = FHIR_CLIENT.search(FHIR::Patient)
    @patients = response.resource&.entry&.map(&:resource) || []
    respond_to do |format|
      format.html
      format.json { render json: @patients }
    end
  end

  def new
    @patient = FHIR::Patient.new
  end

  def create
    @patient = FHIR::Patient.new(patient_params)
    response = FHIR_CLIENT.create(@patient)
    if response.code == 201
      redirect_to fhir_patients_path, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:family, :given, :gender)
  end
end

app/controllers/healthcare_controller.rb
# app/controllers/healthcare_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'googleauth'

class HealthcareController < ApplicationController
  def index
    project_id = "cloud-healthcare-api-425106"
    location = "asia-northeast1"
    dataset_id = "Healthcare_App_Service"
    fhir_store_id = "test-data-store"
    resource_type = "Patient"
    access_token = get_access_token

    uri = URI.parse("https://healthcare.googleapis.com/v1/projects/#{project_id}/locations/#{location}/datasets/#{dataset_id}/fhirStores/#{fhir_store_id}/fhir/#{resource_type}")
    request = Net::HTTP::Get.new(uri)
    request["Authorization"] = "Bearer #{access_token}"
    request["Content-Type"] = "application/json"

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    response = http.request(request)

    if response.code == "200"
      @results = JSON.parse(response.body)
      Rails.logger.info("API Response: #{@results.inspect}")
    else
      @results = nil
      Rails.logger.error("API Request Failed: #{response.message}")
      Rails.logger.error("API Response Body: #{response.body}")
    end
  end

  private

  def get_access_token
    keyfile = File.open(Rails.root.join("config", "service-account-key.json"))
    auth = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: keyfile,
      scope: 'https://www.googleapis.com/auth/cloud-platform'
    )
    auth.fetch_access_token!
    auth.access_token
  end
end

app/controllers/javascripts_controller.rb
class JavascriptsController < ApplicationController
  def show
  end
end

app/controllers/openai/tests_controller.rb
class Openai::TestsController < ApplicationController
  protect_from_forgery

  def show

  end

  def generate_text
    @user_input = params[:user_input]

    if @user_input.present?
      client = OpenAI::Client.new
      response = client.chat(
        parameters: {
          model: "gpt-3.5-turbo",
          messages: [
            { role: "system", content: "関西弁で返答してください" },
            { role: "user", content: @user_input }
          ],
          temperature: 0.7
        }
      )
      @generated_content = response.dig("choices", 0, "message", "content")
      render json:{content: @generated_content}
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)

    result = Geocoder.search(@post.address).first
    if result
      @post.latitude = result.latitude
      @post.longitude = result.longitude
    end

    if  @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "編集が完了しました。"
      redirect_to post_path(@post.id)
    else
      flash[:alert] = "編集ができませんでした。"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def test
    
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :image, :address,)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end

  # サインアウト後のリダイレクト先を指定する
  def after_sign_in_path_for(resource)
    posts_path
  end

  # サインアウト後のリダイレクト先を指定する
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fhir/encounters_helper.rb
module Fhir::EncountersHelper
end

app/helpers/fhir/organizations_helper.rb
module Fhir::OrganizationsHelper
end

app/helpers/fhir/patients_helper.rb
module Fhir::PatientsHelper
end

app/helpers/healthcare_helper.rb
module HealthcareHelper
end

app/helpers/javascripts_helper.rb
module JavascriptsHelper
end

app/helpers/openai/tests_helper.rb
module Openai::TestsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/posts/edit.html.erb
<h1>Hello</h1>

<%= form_with model: @post, url: post_path, method: :patch do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body, "本文" %><br>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit "更新" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Hello</h1>
<% @posts.each do |post| %>
    <%= link_to post.title, post_path(post.id) %>
    <%= post.body %><br>
    <% if post.image.attached? %>
      <%= image_tag post.image, size: "150x150" %><br>
    <%else%>
      <img src="http://placehold.jp/150x150"><br>
    <%end%>
<% end %>

app/views/posts/new.html.erb
<h1>Hello</h1>

<%= form_with model: @post, url: posts_path, method: :post, id: 'post-form' do |f| %>
  <div>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body, "本文" %><br>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.label :images, "画像" %><br>
    <%= f.file_field :image, accept: "image/*" %>
  </div>

  <div>
    <%= f.label :address, "住所" %><br>
    <%= f.text_field :address, id: 'address-input' %>
  </div>

  <div>
    <%= f.submit "投稿" %>
  </div>
<% end %>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['PLACES_API_KEY'] %>&libraries=places"></script>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var addressInput = document.getElementById('address-input');
    var autocomplete = new google.maps.places.Autocomplete(addressInput);

    // 選択された住所をフォームの住所フィールドにセット
    google.maps.event.addListener(autocomplete, 'place_changed', function() {
      var place = autocomplete.getPlace();
      addressInput.value = place.formatted_address;
    });
  });
</script>

app/views/posts/show.html.erb
<h1>Hello</h1>
  <div>
    <div>
      <label for="title">Title</label><br>
      <%= @post.title %>
    </div>

    <div>
      <label for="body">Body</label><br>
      <%= @post.body %>
    </div>

    <div>
    <label for="address">Address</label><br>
    <%= @post.address %>
  </div>

    <div>
      <%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    </div>
  </div>

  <div id="map" style="height: 600px;"></div>

<script>
  function initMap() {
    // 地図要素を取得する（マーカーを表示させるために必要）
    const mapElement = document.getElementById('map');

    const mapOptions = {
      center: {lat: <%= @post.latitude %>, lng: <%= @post.longitude %>},
      zoom: 15
    };

    const map = new google.maps.Map(mapElement, mapOptions);

    // マーカーを追加（Postの情報からマーカーを追加する）
    const maker = new google.maps.Marker({
        position: {lat: <%= @post.latitude %>, lng: <%= @post.longitude %>},
        map: map,
        title: '<%= j @post.title %>'
      });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>&callback=initMap"></script>

  <!--コメントフォーム-->
  <div>
    <%= form_with(model: [@post, Comment.new], url: post_comments_path(@post)) do |f| %>
    <div class="field">
      <%= f.label :body, "コメント追加" %>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit "コメントする" %>
    </div>
    <% end %>
  </div>

  <!--コメントリスト-->
  <div>
    <% @post.comments.each do |comment| %>
      <div>
        <p><%= comment.user.name %></p>
        <p><%= comment.body %></p>
        <p><%= comment.created_at.strftime('%Y/%m/%d') %></p>
      </div>
    <% end %>
  </div>