config/routes.rb
Rails.application.routes.draw do
  get 'javascripts/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  namespace :openai do
    get 'tests/', to: 'tests#generate_text'
    get 'tests/show', to: 'tests#show'
  end

  namespace :fhir do
    resources :patients, only: [:index, :new, :create]
    resources :organizations, only: [:index]
    resources :encounters, only: [:index]
  end

  # Google_Healthcare_API
  get 'healthcare/index', to: 'healthcare#index'
  post 'healthcare/create_patient', to: 'healthcare#create_patient'


  get 'postcode/', to: 'post_codes#show'
end

app/controllers/fhir/encounters_controller.rb
class Fhir::EncountersController < ApplicationController
    def index
    base_url = 'http://example.com/fhir/baseURL'  # FHIRサーバーのベースURLに置き換える
    client = FHIR::Client.new(base_url)
    client.default_json
    response = client.search(FHIR::Encounter)
    @encounters = response.resource.entry.map(&:resource)
  end
end

app/controllers/fhir/organizations_controller.rb
class Fhir::OrganizationsController < ApplicationController
  def index
    client = FHIR::Client.new('http://hapi.fhir.org/baseR4')
    client.default_json
    response = client.search(FHIR::Organization, search: { parameters: { 'address-country': 'Japan' } })
    if response.resource.present?
      @organizations = response.resource.entry.map(&:resource)
    else
      @organizations = []
    end
  end
end

app/controllers/fhir/patients_controller.rb
class Fhir::PatientsController < ApplicationController
  def index
    response = FHIR_CLIENT.search(FHIR::Patient)
    @patients = response.resource&.entry&.map(&:resource) || []
    respond_to do |format|
      format.html
      format.json { render json: @patients }
    end
  end

  def new
    @patient = FHIR::Patient.new
  end

  def create
    @patient = FHIR::Patient.new(patient_params)
    response = FHIR_CLIENT.create(@patient)
    if response.code == 201
      redirect_to fhir_patients_path, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:family, :given, :gender)
  end
end

app/helpers/fhir/encounters_helper.rb
module Fhir::EncountersHelper
end

app/helpers/fhir/organizations_helper.rb
module Fhir::OrganizationsHelper
end

app/helpers/fhir/patients_helper.rb
module Fhir::PatientsHelper
end

app/views/fhir/patients/index.html.erb
<h1>Patients</h1>
<% if notice %>
  <p><%= notice %></p>
<% end %>
<%= link_to 'New Patient', new_fhir_patient_path, class: 'btn btn-primary' %>

<ul>
  <% @patients.each do |patient| %>
    <li>
      <% if patient.name.present? %>
        <% patient_name = patient.name.first %>
        <%= "#{patient_name.family}, #{patient_name.given.join(' ')}" %>
      <% else %>
        No name available for this patient
      <% end %>
      <ul>
        <li><strong>ID:</strong> <%= patient.id %></li>
        <li><strong>Gender:</strong> <%= patient.gender.present? ? patient.gender : "Unknown" %></li>
        <li><strong>Birth Date:</strong> <%= patient.birthDate.present? ? patient.birthDate : "Unknown" %></li>
        <% if patient.address.present? %>
          <li><strong>Address:</strong> <%= patient.address.first.line.join(', ') %>, <%= patient.address.first.city %>, <%= patient.address.first.state %>, <%= patient.address.first.postalCode %>, <%= patient.address.first.country %></li>
        <% else %>
          <li><strong>Address:</strong> Unknown</li>
        <% end %>
        <% if patient.telecom.present? %>
          <li><strong>Contact:</strong> <%= patient.telecom.first.value %></li>
        <% else %>
          <li><strong>Contact:</strong> Unknown</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/fhir/patients/new.html.erb
<%= form_with(url: fhir_patients_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :family %>
    <%= form.text_field :family %>
  </div>
  <div class="field">
    <%= form.label :given %>
    <%= form.text_field :given %>
  </div>
  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, options_for_select(['male', 'female', 'other']) %>
  </div>
  <%= form.submit "Create Patient" %>
<% end %>